{"name": "test_interaction_with_establishments_list", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 20s, while waiting for:\nbrowser.element(('xpath', \"//div[contains(@data-testid, 'about-user-block')]//p[2]\")).element(('xpath', '//div[1]/div[1]/p[2]')).is visible\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@data-testid, 'about-user-block')]//p[2]\"}\n  (Session info: chrome=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x000000010ab22cc8 chromedriver + 4844744\n1   chromedriver                        0x000000010ab1a243 chromedriver + 4809283\n2   chromedriver                        0x000000010a6e877d chromedriver + 411517\n3   chromedriver                        0x000000010a738ee0 chromedriver + 741088\n4   chromedriver                        0x000000010a739091 chromedriver + 741521\n5   chromedriver                        0x000000010a784ab4 chromedriver + 1051316\n6   chromedriver                        0x000000010a762ced chromedriver + 912621\n7   chromedriver                        0x000000010a781d42 chromedriver + 1039682\n8   chromedriver                        0x000000010a762a63 chromedriver + 911971\n9   chromedriver                        0x000000010a72a1b3 chromedriver + 680371\n10  chromedriver                        0x000000010a72b7ce chromedriver + 686030\n11  chromedriver                        0x000000010aae2642 chromedriver + 4580930\n12  chromedriver                        0x000000010aae79cc chromedriver + 4602316\n13  chromedriver                        0x000000010aac7e11 chromedriver + 4472337\n14  chromedriver                        0x000000010aae8746 chromedriver + 4605766\n15  chromedriver                        0x000000010aab939c chromedriver + 4412316\n16  chromedriver                        0x000000010ab08868 chromedriver + 4737128\n17  chromedriver                        0x000000010ab08a1e chromedriver + 4737566\n18  chromedriver                        0x000000010ab19e83 chromedriver + 4808323\n19  libsystem_pthread.dylib             0x00007ff8132701d3 _pthread_start + 125\n20  libsystem_pthread.dylib             0x00007ff81326bbd3 thread_start + 15\n\nScreenshot: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460402.png\nPageSource: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460402.html", "trace": "fn = <selene.core.conditions.ElementCondition object at 0x1133d9360>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n>               return fn(self.entity)\n\nvenv/lib/python3.10/site-packages/selene/core/wait.py:119: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nvenv/lib/python3.10/site-packages/selene/core/condition.py:174: in __call__\n    return self._fn(entity)\nvenv/lib/python3.10/site-packages/selene/core/condition.py:121: in fn\n    if not predicate(entity):\nvenv/lib/python3.10/site-packages/selene/core/match.py:37: in <lambda>\n    'is visible', lambda element: element().is_displayed()\nvenv/lib/python3.10/site-packages/selene/core/entity.py:196: in __call__\n    return self.locate()\nvenv/lib/python3.10/site-packages/selene/core/entity.py:189: in locate\n    return self._locator()\nvenv/lib/python3.10/site-packages/selene/core/locator.py:34: in __call__\n    return self._locate()\nvenv/lib/python3.10/site-packages/selene/core/entity.py:245: in <lambda>\n    Locator(f'{self}.element({by})', lambda: self().find_element(*by)),\nvenv/lib/python3.10/site-packages/selene/core/entity.py:196: in __call__\n    return self.locate()\nvenv/lib/python3.10/site-packages/selene/core/entity.py:189: in locate\n    return self._locator()\nvenv/lib/python3.10/site-packages/selene/core/locator.py:34: in __call__\n    return self._locate()\nvenv/lib/python3.10/site-packages/selene/core/entity.py:1133: in <lambda>\n    Locator(f'{self}.element({by})', lambda: self.driver.find_element(*by)),\nvenv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:738: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\nvenv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x113cfeb00>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...ff8132701d3 _pthread_start + 125\\\\n20  libsystem_pthread.dylib             0x00007ff81326bbd3 thread_start + 15\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@data-testid, 'about-user-block')]//p[2]\"}\nE         (Session info: chrome=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       0   chromedriver                        0x000000010ab22cc8 chromedriver + 4844744\nE       1   chromedriver                        0x000000010ab1a243 chromedriver + 4809283\nE       2   chromedriver                        0x000000010a6e877d chromedriver + 411517\nE       3   chromedriver                        0x000000010a738ee0 chromedriver + 741088\nE       4   chromedriver                        0x000000010a739091 chromedriver + 741521\nE       5   chromedriver                        0x000000010a784ab4 chromedriver + 1051316\nE       6   chromedriver                        0x000000010a762ced chromedriver + 912621\nE       7   chromedriver                        0x000000010a781d42 chromedriver + 1039682\nE       8   chromedriver                        0x000000010a762a63 chromedriver + 911971\nE       9   chromedriver                        0x000000010a72a1b3 chromedriver + 680371\nE       10  chromedriver                        0x000000010a72b7ce chromedriver + 686030\nE       11  chromedriver                        0x000000010aae2642 chromedriver + 4580930\nE       12  chromedriver                        0x000000010aae79cc chromedriver + 4602316\nE       13  chromedriver                        0x000000010aac7e11 chromedriver + 4472337\nE       14  chromedriver                        0x000000010aae8746 chromedriver + 4605766\nE       15  chromedriver                        0x000000010aab939c chromedriver + 4412316\nE       16  chromedriver                        0x000000010ab08868 chromedriver + 4737128\nE       17  chromedriver                        0x000000010ab08a1e chromedriver + 4737566\nE       18  chromedriver                        0x000000010ab19e83 chromedriver + 4808323\nE       19  libsystem_pthread.dylib             0x00007ff8132701d3 _pthread_start + 125\nE       20  libsystem_pthread.dylib             0x00007ff81326bbd3 thread_start + 15\n\nvenv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: NoSuchElementException\n\nDuring handling of the above exception, another exception occurred:\n\n    @allure.title(\"test_interaction_with_establishments_list\")\n    @case_id(7929, 7935)\n    def test_interaction_with_establishments_list():\n        user_management = UserManagementActions()\n        owner = owner_account\n        user = delegator_for_edit_flow\n        log_in_and_open_user_management(owner, Language.EN)\n>       user_management.navigate_to_user_details(user.personal_number) \\\n            .select_all_allowed_access_establishments_checkbox() \\\n            .unselect_all_allowed_access_establishments_checkbox() \\\n            .select_allowed_access_establishment_checkbox() \\\n            .check_establishment_checkbox_is_selected_after_switching_between_tabs()\n\ntests/ui/user_management/test_user_management.py:246: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc/ui/actions/user_management_actions/user_management.py:97: in navigate_to_user_details\n    self.check_users_info_block()\nsrc/ui/pages/user_management_pages/user_detail_page.py:90: in check_users_info_block\n    self.subscribed_user_name.should(be.visible)\nvenv/lib/python3.10/site-packages/selene/core/entity.py:136: in should\n    self.wait.for_(condition)\nvenv/lib/python3.10/site-packages/selene/core/wait.py:143: in for_\n    return self._decorator(self)(logic)(fn)\nvenv/lib/python3.10/site-packages/selene/support/_logging.py:105: in decorated\n    return for_(fn)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nfn = <selene.core.conditions.ElementCondition object at 0x1133d9360>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n                return fn(self.entity)\n            except Exception as reason:\n                if time.time() > finish_time:\n                    reason_message = str(reason)\n    \n                    reason_string = '{name}: {message}'.format(\n                        name=reason.__class__.__name__,\n                        message=reason_message,\n                    )\n                    # TODO: think on how can we improve logging failures in selene, e.g. reverse msg and stacktrace\n                    # stacktrace = getattr(reason, 'stacktrace', None)\n                    timeout = self._timeout\n                    entity = self.entity\n    \n                    failure = TimeoutException(\n                        f'\\n'\n                        f'\\nTimed out after {timeout}s, while waiting for:'\n                        f'\\n{entity}.{fn}'\n                        f'\\n'\n                        f'\\nReason: {reason_string}'\n                    )\n    \n>                   raise self._hook_failure(failure)\nE                   selene.core.exceptions.TimeoutException: Message: \nE                   \nE                   Timed out after 20s, while waiting for:\nE                   browser.element(('xpath', \"//div[contains(@data-testid, 'about-user-block')]//p[2]\")).element(('xpath', '//div[1]/div[1]/p[2]')).is visible\nE                   \nE                   Reason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@data-testid, 'about-user-block')]//p[2]\"}\nE                     (Session info: chrome=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE                   Stacktrace:\nE                   0   chromedriver                        0x000000010ab22cc8 chromedriver + 4844744\nE                   1   chromedriver                        0x000000010ab1a243 chromedriver + 4809283\nE                   2   chromedriver                        0x000000010a6e877d chromedriver + 411517\nE                   3   chromedriver                        0x000000010a738ee0 chromedriver + 741088\nE                   4   chromedriver                        0x000000010a739091 chromedriver + 741521\nE                   5   chromedriver                        0x000000010a784ab4 chromedriver + 1051316\nE                   6   chromedriver                        0x000000010a762ced chromedriver + 912621\nE                   7   chromedriver                        0x000000010a781d42 chromedriver + 1039682\nE                   8   chromedriver                        0x000000010a762a63 chromedriver + 911971\nE                   9   chromedriver                        0x000000010a72a1b3 chromedriver + 680371\nE                   10  chromedriver                        0x000000010a72b7ce chromedriver + 686030\nE                   11  chromedriver                        0x000000010aae2642 chromedriver + 4580930\nE                   12  chromedriver                        0x000000010aae79cc chromedriver + 4602316\nE                   13  chromedriver                        0x000000010aac7e11 chromedriver + 4472337\nE                   14  chromedriver                        0x000000010aae8746 chromedriver + 4605766\nE                   15  chromedriver                        0x000000010aab939c chromedriver + 4412316\nE                   16  chromedriver                        0x000000010ab08868 chromedriver + 4737128\nE                   17  chromedriver                        0x000000010ab08a1e chromedriver + 4737566\nE                   18  chromedriver                        0x000000010ab19e83 chromedriver + 4808323\nE                   19  libsystem_pthread.dylib             0x00007ff8132701d3 _pthread_start + 125\nE                   20  libsystem_pthread.dylib             0x00007ff81326bbd3 thread_start + 15\nE                   \nE                   Screenshot: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460402.png\nE                   PageSource: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460402.html\n\nvenv/lib/python3.10/site-packages/selene/core/wait.py:141: TimeoutException"}, "steps": [{"name": "login_as_user", "status": "passed", "steps": [{"name": "Login '1001530987' via Laborer SSO API", "status": "passed", "steps": [{"name": "[200] POST /oauth/init", "status": "passed", "attachments": [{"name": "JSON Request body", "source": "6c9de3a2-5fd4-4712-a4b2-d2c402223edc-attachment.json", "type": "application/json"}, {"name": "JSON Response body", "source": "22971324-d87b-4ad4-8d70-59928c9ff8e6-attachment.json", "type": "application/json"}], "start": 1703165959862, "stop": 1703165959865}, {"name": "Assert that status_code equals 200", "status": "passed", "start": 1703165959865, "stop": 1703165959865}, {"name": "login", "status": "passed", "steps": [{"name": "[200] POST /session/login", "status": "passed", "attachments": [{"name": "JSON Request body", "source": "698420df-6d21-4f91-b381-6b4af70a0467-attachment.json", "type": "application/json"}, {"name": "JSON Response body", "source": "2adcd1e2-ba76-4db0-bde4-ff0d7b73de1f-attachment.json", "type": "application/json"}], "start": 1703165960846, "stop": 1703165960876}, {"name": "Assert that status_code equals 200", "status": "passed", "start": 1703165960877, "stop": 1703165960877}], "parameters": [{"name": "login", "value": "'1001530987'"}, {"name": "password", "value": "'123456789aA@'"}, {"name": "expected_code", "value": "200"}], "start": 1703165959866, "stop": 1703165960877}, {"name": "login_with_otp", "status": "passed", "steps": [{"name": "[200] POST /session/login-with-otp", "status": "passed", "attachments": [{"name": "JSON Request body", "source": "58fac053-e27c-418d-8358-825719f975ca-attachment.json", "type": "application/json"}, {"name": "JSON Response body", "source": "153126f9-8ad0-4daf-8f94-f102b104e9e6-attachment.json", "type": "application/json"}], "start": 1703165961389, "stop": 1703165961421}, {"name": "Assert that status_code equals 200", "status": "passed", "start": 1703165961422, "stop": 1703165961422}], "parameters": [{"name": "otp_code", "value": "'0000'"}, {"name": "expected_code", "value": "200"}], "start": 1703165960878, "stop": 1703165961422}, {"name": "[302] POST /authorize?client_id=qiwa&redirect_uri=https%3A%2F%2Fauth.qiwa.info%2Foauth%2Fcallback&response_type=code&scope=openid+email+phone+profile&code_challenge_method=S256&state=Uv-B695qRssmcbbkB4bMmz3AN8itRWsEtd-RC7cA7e4&code_challenge=NpsBGH9vim0jODcB0XT4ndSy9yuIyQZ-FkQ4nh2XC64", "status": "passed", "start": 1703165961558, "stop": 1703165961558}, {"name": "Assert that status_code equals 302", "status": "passed", "start": 1703165961564, "stop": 1703165961564}, {"name": "[200] POST /oauth/callback", "status": "passed", "attachments": [{"name": "JSON Request body", "source": "a76346a8-bf86-46de-8852-2d7e15802fb3-attachment.json", "type": "application/json"}, {"name": "JSON Response body", "source": "9c4310bf-ddb0-4548-9cb5-7c7df68234ee-attachment.json", "type": "application/json"}], "start": 1703165962476, "stop": 1703165962478}, {"name": "Assert that status_code equals 200", "status": "passed", "start": 1703165962479, "stop": 1703165962479}], "parameters": [{"name": "personal_number", "value": "'1001530987'"}, {"name": "password", "value": "'123456789aA@'"}], "start": 1703165959267, "stop": 1703165962479}], "parameters": [{"name": "personal_number", "value": "'1001530987'"}, {"name": "password", "value": "'123456789aA@'"}], "start": 1703165959266, "stop": 1703165962479}, {"name": "select_company", "status": "passed", "steps": [{"name": "select_company_with_sequence_number", "status": "passed", "steps": [{"name": "get_workspaces", "status": "passed", "steps": [{"name": "[200] GET /context/workspaces", "status": "passed", "attachments": [{"name": "JSON Response body", "source": "5677e9e6-fae4-4d33-a037-a06e9be77b37-attachment.json", "type": "application/json"}], "start": 1703165963514, "stop": 1703165963516}], "start": 1703165962480, "stop": 1703165963517}, {"name": "select_company_by_id", "status": "passed", "steps": [{"name": "[200] PATCH /context/company/12652", "status": "passed", "start": 1703165964763, "stop": 1703165964763}], "parameters": [{"name": "company_id", "value": "12652"}, {"name": "status_code", "value": "200"}], "start": 1703165963518, "stop": 1703165964764}], "parameters": [{"name": "number", "value": "1910"}], "start": 1703165962479, "stop": 1703165964764}], "parameters": [{"name": "sequence_number", "value": "1910"}], "start": 1703165962479, "stop": 1703165964764}, {"name": "[200] GET /context", "status": "passed", "attachments": [{"name": "JSON Response body", "source": "9d79fd0e-7c15-41df-baf0-e7234a5ab43e-attachment.json", "type": "application/json"}], "start": 1703165965014, "stop": 1703165965016}, {"name": "Assert that status_code equals 200", "status": "passed", "start": 1703165965017, "stop": 1703165965017}, {"name": "open_user_management_page", "status": "passed", "start": 1703165965017, "stop": 1703165965810}, {"name": "element('xpath', \"//div[contains(@data-testid, 'user-table')]//tbody\"): should be visible", "status": "passed", "start": 1703165965819, "stop": 1703165978950}, {"name": "change_local", "status": "passed", "steps": [{"name": "change_local", "status": "passed", "steps": [{"name": "element('xpath', '//*[@data-component=\"Navigation\"]//p[contains(text(), \"AR\") or contains(text(), \"EN\") or contains(text(), \"ع\")]'): click", "status": "passed", "start": 1703165978951, "stop": 1703165979036}, {"name": "element('xpath', '//p[contains(text(), \"English (EN)\")]'): click", "status": "passed", "start": 1703165979036, "stop": 1703165979089}], "parameters": [{"name": "language", "value": "'en'"}], "start": 1703165978951, "stop": 1703165979089}], "parameters": [{"name": "a", "value": "(<src.ui.components.header.Header object at 0x113a29cc0>, 'en')"}], "start": 1703165978950, "stop": 1703165979089}, {"name": "navigate_to_user_details", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 20s, while waiting for:\nbrowser.element(('xpath', \"//div[contains(@data-testid, 'about-user-block')]//p[2]\")).element(('xpath', '//div[1]/div[1]/p[2]')).is visible\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@data-testid, 'about-user-block')]//p[2]\"}\n  (Session info: chrome=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x000000010ab22cc8 chromedriver + 4844744\n1   chromedriver                        0x000000010ab1a243 chromedriver + 4809283\n2   chromedriver                        0x000000010a6e877d chromedriver + 411517\n3   chromedriver                        0x000000010a738ee0 chromedriver + 741088\n4   chromedriver                        0x000000010a739091 chromedriver + 741521\n5   chromedriver                        0x000000010a784ab4 chromedriver + 1051316\n6   chromedriver                        0x000000010a762ced chromedriver + 912621\n7   chromedriver                        0x000000010a781d42 chromedriver + 1039682\n8   chromedriver                        0x000000010a762a63 chromedriver + 911971\n9   chromedriver                        0x000000010a72a1b3 chromedriver + 680371\n10  chromedriver                        0x000000010a72b7ce chromedriver + 686030\n11  chromedriver                        0x000000010aae2642 chromedriver + 4580930\n12  chromedriver                        0x000000010aae79cc chromedriver + 4602316\n13  chromedriver                        0x000000010aac7e11 chromedriver + 4472337\n14  chromedriver                        0x000000010aae8746 chromedriver + 4605766\n15  chromedriver                        0x000000010aab939c chromedriver + 4412316\n16  chromedriver                        0x000000010ab08868 chromedriver + 4737128\n17  chromedriver                        0x000000010ab08a1e chromedriver + 4737566\n18  chromedriver                        0x000000010ab19e83 chromedriver + 4808323\n19  libsystem_pthread.dylib             0x00007ff8132701d3 _pthread_start + 125\n20  libsystem_pthread.dylib             0x00007ff81326bbd3 thread_start + 15\n\nScreenshot: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460402.png\nPageSource: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460402.html\n\n", "trace": "  File \"/Users/olehlazeba/PycharmProjects/qiwa-automation/venv/lib/python3.10/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/olehlazeba/PycharmProjects/qiwa-automation/src/ui/actions/user_management_actions/user_management.py\", line 97, in navigate_to_user_details\n    self.check_users_info_block()\n  File \"/Users/olehlazeba/PycharmProjects/qiwa-automation/src/ui/pages/user_management_pages/user_detail_page.py\", line 90, in check_users_info_block\n    self.subscribed_user_name.should(be.visible)\n  File \"/Users/olehlazeba/PycharmProjects/qiwa-automation/venv/lib/python3.10/site-packages/selene/core/entity.py\", line 136, in should\n    self.wait.for_(condition)\n  File \"/Users/olehlazeba/PycharmProjects/qiwa-automation/venv/lib/python3.10/site-packages/selene/core/wait.py\", line 143, in for_\n    return self._decorator(self)(logic)(fn)\n  File \"/Users/olehlazeba/PycharmProjects/qiwa-automation/venv/lib/python3.10/site-packages/selene/support/_logging.py\", line 105, in decorated\n    return for_(fn)\n  File \"/Users/olehlazeba/PycharmProjects/qiwa-automation/venv/lib/python3.10/site-packages/selene/core/wait.py\", line 141, in logic\n    raise self._hook_failure(failure)\n"}, "steps": [{"name": "open_user_details_page", "status": "passed", "parameters": [{"name": "personal_number", "value": "'1096471568'"}], "start": 1703165979091, "stop": 1703165979291}, {"name": "element('xpath', \"//div[contains(@data-testid, 'about-user-block')]//p[2]\").element('xpath', '//div[1]/div[1]/p[2]'): should be visible", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 20s, while waiting for:\nbrowser.element(('xpath', \"//div[contains(@data-testid, 'about-user-block')]//p[2]\")).element(('xpath', '//div[1]/div[1]/p[2]')).is visible\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@data-testid, 'about-user-block')]//p[2]\"}\n  (Session info: chrome=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x000000010ab22cc8 chromedriver + 4844744\n1   chromedriver                        0x000000010ab1a243 chromedriver + 4809283\n2   chromedriver                        0x000000010a6e877d chromedriver + 411517\n3   chromedriver                        0x000000010a738ee0 chromedriver + 741088\n4   chromedriver                        0x000000010a739091 chromedriver + 741521\n5   chromedriver                        0x000000010a784ab4 chromedriver + 1051316\n6   chromedriver                        0x000000010a762ced chromedriver + 912621\n7   chromedriver                        0x000000010a781d42 chromedriver + 1039682\n8   chromedriver                        0x000000010a762a63 chromedriver + 911971\n9   chromedriver                        0x000000010a72a1b3 chromedriver + 680371\n10  chromedriver                        0x000000010a72b7ce chromedriver + 686030\n11  chromedriver                        0x000000010aae2642 chromedriver + 4580930\n12  chromedriver                        0x000000010aae79cc chromedriver + 4602316\n13  chromedriver                        0x000000010aac7e11 chromedriver + 4472337\n14  chromedriver                        0x000000010aae8746 chromedriver + 4605766\n15  chromedriver                        0x000000010aab939c chromedriver + 4412316\n16  chromedriver                        0x000000010ab08868 chromedriver + 4737128\n17  chromedriver                        0x000000010ab08a1e chromedriver + 4737566\n18  chromedriver                        0x000000010ab19e83 chromedriver + 4808323\n19  libsystem_pthread.dylib             0x00007ff8132701d3 _pthread_start + 125\n20  libsystem_pthread.dylib             0x00007ff81326bbd3 thread_start + 15\n\nScreenshot: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460402.png\nPageSource: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460402.html\n\n", "trace": "  File \"/Users/olehlazeba/PycharmProjects/qiwa-automation/venv/lib/python3.10/site-packages/selene/support/_logging.py\", line 105, in decorated\n    return for_(fn)\n  File \"/Users/olehlazeba/PycharmProjects/qiwa-automation/venv/lib/python3.10/site-packages/selene/core/wait.py\", line 141, in logic\n    raise self._hook_failure(failure)\n"}, "start": 1703165979291, "stop": 1703165999541}], "parameters": [{"name": "personal_number", "value": "'1096471568'"}], "start": 1703165979091, "stop": 1703165999541}], "attachments": [{"name": "2023-12-21 15:39:59.624909.png", "source": "9a0d5af0-0698-4d9f-8e60-4bf359af99d1-attachment.png", "type": "image/png"}], "start": 1703165959265, "stop": 1703165999542, "uuid": "c439a922-1ae3-463c-b93b-3dddd3356ef1", "historyId": "50156a68a8cf240b79e835f6885767d0", "testCaseId": "50156a68a8cf240b79e835f6885767d0", "fullName": "tests.ui.user_management.test_user_management#test_interaction_with_establishments_list", "labels": [{"name": "parentSuite", "value": "tests.ui.user_management"}, {"name": "suite", "value": "test_user_management"}, {"name": "host", "value": "Macbook-Pro-Flora.local"}, {"name": "thread", "value": "54235-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.user_management.test_user_management"}], "links": [{"type": "tms", "url": "https://qiwa.testmo.net/repositories/26?case_id=7929", "name": "Testmo test case (7929)"}, {"type": "tms", "url": "https://qiwa.testmo.net/repositories/26?case_id=7935", "name": "Testmo test case (7935)"}]}