{"name": "Check that user without UM privileges can't open UM service", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 20s, while waiting for:\nbrowser.element(('xpath', \"//div[contains(@data-testid, 'user-table')]//tbody\")).is visible\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@data-testid, 'user-table')]//tbody\"}\n  (Session info: chrome=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x000000010d5a7cc8 chromedriver + 4844744\n1   chromedriver                        0x000000010d59f243 chromedriver + 4809283\n2   chromedriver                        0x000000010d16d77d chromedriver + 411517\n3   chromedriver                        0x000000010d1bdee0 chromedriver + 741088\n4   chromedriver                        0x000000010d1be091 chromedriver + 741521\n5   chromedriver                        0x000000010d209ab4 chromedriver + 1051316\n6   chromedriver                        0x000000010d1e7ced chromedriver + 912621\n7   chromedriver                        0x000000010d206d42 chromedriver + 1039682\n8   chromedriver                        0x000000010d1e7a63 chromedriver + 911971\n9   chromedriver                        0x000000010d1af1b3 chromedriver + 680371\n10  chromedriver                        0x000000010d1b07ce chromedriver + 686030\n11  chromedriver                        0x000000010d567642 chromedriver + 4580930\n12  chromedriver                        0x000000010d56c9cc chromedriver + 4602316\n13  chromedriver                        0x000000010d54ce11 chromedriver + 4472337\n14  chromedriver                        0x000000010d56d746 chromedriver + 4605766\n15  chromedriver                        0x000000010d53e39c chromedriver + 4412316\n16  chromedriver                        0x000000010d58d868 chromedriver + 4737128\n17  chromedriver                        0x000000010d58da1e chromedriver + 4737566\n18  chromedriver                        0x000000010d59ee83 chromedriver + 4808323\n19  libsystem_pthread.dylib             0x00007ff8132701d3 _pthread_start + 125\n20  libsystem_pthread.dylib             0x00007ff81326bbd3 thread_start + 15\n\nScreenshot: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460399.png\nPageSource: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460399.html", "trace": "fn = <selene.core.conditions.ElementCondition object at 0x1133d9360>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n>               return fn(self.entity)\n\nvenv/lib/python3.10/site-packages/selene/core/wait.py:119: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nvenv/lib/python3.10/site-packages/selene/core/condition.py:174: in __call__\n    return self._fn(entity)\nvenv/lib/python3.10/site-packages/selene/core/condition.py:121: in fn\n    if not predicate(entity):\nvenv/lib/python3.10/site-packages/selene/core/match.py:37: in <lambda>\n    'is visible', lambda element: element().is_displayed()\nvenv/lib/python3.10/site-packages/selene/core/entity.py:196: in __call__\n    return self.locate()\nvenv/lib/python3.10/site-packages/selene/core/entity.py:189: in locate\n    return self._locator()\nvenv/lib/python3.10/site-packages/selene/core/locator.py:34: in __call__\n    return self._locate()\nvenv/lib/python3.10/site-packages/selene/core/entity.py:1133: in <lambda>\n    Locator(f'{self}.element({by})', lambda: self.driver.find_element(*by)),\nvenv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:738: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\nvenv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x113b8a800>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...ff8132701d3 _pthread_start + 125\\\\n20  libsystem_pthread.dylib             0x00007ff81326bbd3 thread_start + 15\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@data-testid, 'user-table')]//tbody\"}\nE         (Session info: chrome=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       0   chromedriver                        0x000000010d5a7cc8 chromedriver + 4844744\nE       1   chromedriver                        0x000000010d59f243 chromedriver + 4809283\nE       2   chromedriver                        0x000000010d16d77d chromedriver + 411517\nE       3   chromedriver                        0x000000010d1bdee0 chromedriver + 741088\nE       4   chromedriver                        0x000000010d1be091 chromedriver + 741521\nE       5   chromedriver                        0x000000010d209ab4 chromedriver + 1051316\nE       6   chromedriver                        0x000000010d1e7ced chromedriver + 912621\nE       7   chromedriver                        0x000000010d206d42 chromedriver + 1039682\nE       8   chromedriver                        0x000000010d1e7a63 chromedriver + 911971\nE       9   chromedriver                        0x000000010d1af1b3 chromedriver + 680371\nE       10  chromedriver                        0x000000010d1b07ce chromedriver + 686030\nE       11  chromedriver                        0x000000010d567642 chromedriver + 4580930\nE       12  chromedriver                        0x000000010d56c9cc chromedriver + 4602316\nE       13  chromedriver                        0x000000010d54ce11 chromedriver + 4472337\nE       14  chromedriver                        0x000000010d56d746 chromedriver + 4605766\nE       15  chromedriver                        0x000000010d53e39c chromedriver + 4412316\nE       16  chromedriver                        0x000000010d58d868 chromedriver + 4737128\nE       17  chromedriver                        0x000000010d58da1e chromedriver + 4737566\nE       18  chromedriver                        0x000000010d59ee83 chromedriver + 4808323\nE       19  libsystem_pthread.dylib             0x00007ff8132701d3 _pthread_start + 125\nE       20  libsystem_pthread.dylib             0x00007ff81326bbd3 thread_start + 15\n\nvenv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: NoSuchElementException\n\nDuring handling of the above exception, another exception occurred:\n\n    @allure.title(\"Check that user without UM privileges can't open UM service\")\n    @case_id(7872, 7882, 7931)\n    # TODO: update test based on test case 7882\n    def test_error_for_user_without_um_service():\n        user = delegator_without_um\n        employee = user_type_three_employee\n        user_management = UserManagementActions()\n        log_in_and_open_user_management(user, Language.EN, False)\n        user_management.check_error_message_for_um_page_without_permission(\n            ErrorsMessage.user_doesnt_have_access_to_um, ErrorsMessage.no_access_error_description\n        ).navigate_to_user_details_without_um_permission(employee.personal_number) \\\n            .click_header_main_menu_btn().click_change_workspace_btn()\n        qiwa.workspace_page.select_company_account_with_sequence_number(sequence_number=\"157949\")\n        qiwa.open_user_management_page()\n>       qiwa.main_page.check_page_is_displayed()\n\ntests/ui/user_management/test_user_management.py:144: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nsrc/ui/pages/user_management_pages/main_page.py:68: in check_page_is_displayed\n    self.users_in_table.should(be.visible)\nvenv/lib/python3.10/site-packages/selene/core/entity.py:136: in should\n    self.wait.for_(condition)\nvenv/lib/python3.10/site-packages/selene/core/wait.py:143: in for_\n    return self._decorator(self)(logic)(fn)\nvenv/lib/python3.10/site-packages/selene/support/_logging.py:105: in decorated\n    return for_(fn)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nfn = <selene.core.conditions.ElementCondition object at 0x1133d9360>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n                return fn(self.entity)\n            except Exception as reason:\n                if time.time() > finish_time:\n                    reason_message = str(reason)\n    \n                    reason_string = '{name}: {message}'.format(\n                        name=reason.__class__.__name__,\n                        message=reason_message,\n                    )\n                    # TODO: think on how can we improve logging failures in selene, e.g. reverse msg and stacktrace\n                    # stacktrace = getattr(reason, 'stacktrace', None)\n                    timeout = self._timeout\n                    entity = self.entity\n    \n                    failure = TimeoutException(\n                        f'\\n'\n                        f'\\nTimed out after {timeout}s, while waiting for:'\n                        f'\\n{entity}.{fn}'\n                        f'\\n'\n                        f'\\nReason: {reason_string}'\n                    )\n    \n>                   raise self._hook_failure(failure)\nE                   selene.core.exceptions.TimeoutException: Message: \nE                   \nE                   Timed out after 20s, while waiting for:\nE                   browser.element(('xpath', \"//div[contains(@data-testid, 'user-table')]//tbody\")).is visible\nE                   \nE                   Reason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@data-testid, 'user-table')]//tbody\"}\nE                     (Session info: chrome=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE                   Stacktrace:\nE                   0   chromedriver                        0x000000010d5a7cc8 chromedriver + 4844744\nE                   1   chromedriver                        0x000000010d59f243 chromedriver + 4809283\nE                   2   chromedriver                        0x000000010d16d77d chromedriver + 411517\nE                   3   chromedriver                        0x000000010d1bdee0 chromedriver + 741088\nE                   4   chromedriver                        0x000000010d1be091 chromedriver + 741521\nE                   5   chromedriver                        0x000000010d209ab4 chromedriver + 1051316\nE                   6   chromedriver                        0x000000010d1e7ced chromedriver + 912621\nE                   7   chromedriver                        0x000000010d206d42 chromedriver + 1039682\nE                   8   chromedriver                        0x000000010d1e7a63 chromedriver + 911971\nE                   9   chromedriver                        0x000000010d1af1b3 chromedriver + 680371\nE                   10  chromedriver                        0x000000010d1b07ce chromedriver + 686030\nE                   11  chromedriver                        0x000000010d567642 chromedriver + 4580930\nE                   12  chromedriver                        0x000000010d56c9cc chromedriver + 4602316\nE                   13  chromedriver                        0x000000010d54ce11 chromedriver + 4472337\nE                   14  chromedriver                        0x000000010d56d746 chromedriver + 4605766\nE                   15  chromedriver                        0x000000010d53e39c chromedriver + 4412316\nE                   16  chromedriver                        0x000000010d58d868 chromedriver + 4737128\nE                   17  chromedriver                        0x000000010d58da1e chromedriver + 4737566\nE                   18  chromedriver                        0x000000010d59ee83 chromedriver + 4808323\nE                   19  libsystem_pthread.dylib             0x00007ff8132701d3 _pthread_start + 125\nE                   20  libsystem_pthread.dylib             0x00007ff81326bbd3 thread_start + 15\nE                   \nE                   Screenshot: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460399.png\nE                   PageSource: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460399.html\n\nvenv/lib/python3.10/site-packages/selene/core/wait.py:141: TimeoutException"}, "steps": [{"name": "login_as_user", "status": "passed", "steps": [{"name": "Login '1014157000' via Laborer SSO API", "status": "passed", "steps": [{"name": "[200] POST /oauth/init", "status": "passed", "attachments": [{"name": "JSON Request body", "source": "03e8dcc5-fcde-490d-9f68-560fcb15ac6f-attachment.json", "type": "application/json"}, {"name": "JSON Response body", "source": "d1a152bc-43df-4b77-8c17-cfdec713ab24-attachment.json", "type": "application/json"}], "start": 1703165721706, "stop": 1703165721708}, {"name": "Assert that status_code equals 200", "status": "passed", "start": 1703165721709, "stop": 1703165721709}, {"name": "login", "status": "passed", "steps": [{"name": "[200] POST /session/login", "status": "passed", "attachments": [{"name": "JSON Request body", "source": "b352437c-94a2-42bc-b7a0-31a0a864da77-attachment.json", "type": "application/json"}, {"name": "JSON Response body", "source": "0e998a21-5d39-49bb-a16f-c23822ddcfad-attachment.json", "type": "application/json"}], "start": 1703165722829, "stop": 1703165722865}, {"name": "Assert that status_code equals 200", "status": "passed", "start": 1703165722866, "stop": 1703165722866}], "parameters": [{"name": "login", "value": "'1014157000'"}, {"name": "password", "value": "'123456789aA@'"}, {"name": "expected_code", "value": "200"}], "start": 1703165721710, "stop": 1703165722866}, {"name": "login_with_otp", "status": "passed", "steps": [{"name": "[200] POST /session/login-with-otp", "status": "passed", "attachments": [{"name": "JSON Request body", "source": "38c478b5-e83f-4068-8179-0c28d0503d26-attachment.json", "type": "application/json"}, {"name": "JSON Response body", "source": "0b677355-9052-45bf-95e5-4b545ed3dfb7-attachment.json", "type": "application/json"}], "start": 1703165723381, "stop": 1703165723411}, {"name": "Assert that status_code equals 200", "status": "passed", "start": 1703165723412, "stop": 1703165723412}], "parameters": [{"name": "otp_code", "value": "'0000'"}, {"name": "expected_code", "value": "200"}], "start": 1703165722867, "stop": 1703165723412}, {"name": "[302] POST /authorize?client_id=qiwa&redirect_uri=https%3A%2F%2Fauth.qiwa.info%2Foauth%2Fcallback&response_type=code&scope=openid+email+phone+profile&code_challenge_method=S256&state=QffPqQbxocKjXh21su78bg_lxw6O2imk1YOZxJqaulY&code_challenge=OuAJo_wpQInmaP5BwXUSpgmDfBLiEGzHxrHIdzSNKwU", "status": "passed", "start": 1703165723550, "stop": 1703165723550}, {"name": "Assert that status_code equals 302", "status": "passed", "start": 1703165723556, "stop": 1703165723556}, {"name": "[200] POST /oauth/callback", "status": "passed", "attachments": [{"name": "JSON Request body", "source": "953945ee-45e3-405f-9e53-94f83204c666-attachment.json", "type": "application/json"}, {"name": "JSON Response body", "source": "eee3be55-ea7f-47fb-a1b4-e682412ff5d9-attachment.json", "type": "application/json"}], "start": 1703165724815, "stop": 1703165724818}, {"name": "Assert that status_code equals 200", "status": "passed", "start": 1703165724818, "stop": 1703165724818}], "parameters": [{"name": "personal_number", "value": "'1014157000'"}, {"name": "password", "value": "'123456789aA@'"}], "start": 1703165721100, "stop": 1703165724819}], "parameters": [{"name": "personal_number", "value": "'1014157000'"}, {"name": "password", "value": "'123456789aA@'"}], "start": 1703165721099, "stop": 1703165724819}, {"name": "select_company", "status": "passed", "steps": [{"name": "select_company_with_sequence_number", "status": "passed", "steps": [{"name": "get_workspaces", "status": "passed", "steps": [{"name": "[200] GET /context/workspaces", "status": "passed", "attachments": [{"name": "JSON Response body", "source": "0bf03ec0-7e0b-46dd-9505-eea87e0ebea9-attachment.json", "type": "application/json"}], "start": 1703165725711, "stop": 1703165725714}], "start": 1703165724819, "stop": 1703165725714}, {"name": "select_company_by_id", "status": "passed", "steps": [{"name": "[200] PATCH /context/company/31100", "status": "passed", "start": 1703165727171, "stop": 1703165727171}], "parameters": [{"name": "company_id", "value": "31100"}, {"name": "status_code", "value": "200"}], "start": 1703165725715, "stop": 1703165727172}], "parameters": [{"name": "number", "value": "1196371"}], "start": 1703165724819, "stop": 1703165727172}], "parameters": [{"name": "sequence_number", "value": "1196371"}], "start": 1703165724819, "stop": 1703165727172}, {"name": "[200] GET /context", "status": "passed", "attachments": [{"name": "JSON Response body", "source": "36196906-5017-47bc-8029-a93ce29f14f4-attachment.json", "type": "application/json"}], "start": 1703165727345, "stop": 1703165727347}, {"name": "Assert that status_code equals 200", "status": "passed", "start": 1703165727347, "stop": 1703165727347}, {"name": "open_user_management_page", "status": "passed", "start": 1703165727348, "stop": 1703165728229}, {"name": "change_local", "status": "passed", "steps": [{"name": "change_local", "status": "passed", "steps": [{"name": "element('xpath', '//*[@data-component=\"Navigation\"]//p[contains(text(), \"AR\") or contains(text(), \"EN\") or contains(text(), \"ع\")]'): click", "status": "passed", "start": 1703165728238, "stop": 1703165734729}, {"name": "element('xpath', '//p[contains(text(), \"English (EN)\")]'): click", "status": "passed", "start": 1703165734729, "stop": 1703165734778}], "parameters": [{"name": "language", "value": "'en'"}], "start": 1703165728238, "stop": 1703165734778}], "parameters": [{"name": "a", "value": "(<src.ui.components.header.Header object at 0x113a29cc0>, 'en')"}], "start": 1703165728238, "stop": 1703165734778}, {"name": "element('xpath', \"//div[contains(@data-testid,'global-error')]/div/p[1]\"): should have text Sorry! You need permission to enter this page", "status": "passed", "start": 1703165734780, "stop": 1703165734816}, {"name": "element('xpath', \"//div[contains(@data-testid,'global-error')]/div/p[2]\"): should have text You have no permission to access this part of the platform.", "status": "passed", "start": 1703165734816, "stop": 1703165734830}, {"name": "navigate_to_user_details_without_um_permission", "status": "passed", "steps": [{"name": "open_user_details_page", "status": "passed", "parameters": [{"name": "personal_number", "value": "'1070111305'"}], "start": 1703165734830, "stop": 1703165735031}, {"name": "element('xpath', \"//div[contains(@data-testid,'global-error')]/div/p[1]\"): should have text Sorry! You need permission to enter this page", "status": "passed", "start": 1703165735031, "stop": 1703165736140}, {"name": "element('xpath', \"//div[contains(@data-testid,'global-error')]/div/p[2]\"): should have text You have no permission to access this part of the platform.", "status": "passed", "start": 1703165736140, "stop": 1703165736150}], "parameters": [{"name": "personal_number", "value": "'1070111305'"}], "start": 1703165734830, "stop": 1703165736151}, {"name": "element('xpath', \"//div[contains(@data-testid, 'menu-trigger')]/div/button\"): click", "status": "passed", "start": 1703165736151, "stop": 1703165736231}, {"name": "element('xpath', \"//div[contains(@class, 'tippy-content')]//div[3]//a\"): click", "status": "passed", "start": 1703165736231, "stop": 1703165737245}, {"name": "select_company_account_with_sequence_number", "status": "passed", "steps": [{"name": "select_business_account", "status": "passed", "steps": [{"name": "all(\"[data-component='Tile']\").element_by(has text Business Account): click", "status": "passed", "start": 1703165737246, "stop": 1703165739722}], "start": 1703165737245, "stop": 1703165739722}, {"name": "all(\"[data-component='TabPanel'] button\").element_by(has text 157949): click", "status": "passed", "start": 1703165739722, "stop": 1703165740715}], "parameters": [{"name": "sequence_number", "value": "'157949'"}], "start": 1703165737245, "stop": 1703165740715}, {"name": "open_user_management_page", "status": "passed", "start": 1703165740715, "stop": 1703165740885}, {"name": "element('xpath', \"//div[contains(@data-testid, 'user-table')]//tbody\"): should be visible", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 20s, while waiting for:\nbrowser.element(('xpath', \"//div[contains(@data-testid, 'user-table')]//tbody\")).is visible\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//div[contains(@data-testid, 'user-table')]//tbody\"}\n  (Session info: chrome=120.0.6099.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x000000010d5a7cc8 chromedriver + 4844744\n1   chromedriver                        0x000000010d59f243 chromedriver + 4809283\n2   chromedriver                        0x000000010d16d77d chromedriver + 411517\n3   chromedriver                        0x000000010d1bdee0 chromedriver + 741088\n4   chromedriver                        0x000000010d1be091 chromedriver + 741521\n5   chromedriver                        0x000000010d209ab4 chromedriver + 1051316\n6   chromedriver                        0x000000010d1e7ced chromedriver + 912621\n7   chromedriver                        0x000000010d206d42 chromedriver + 1039682\n8   chromedriver                        0x000000010d1e7a63 chromedriver + 911971\n9   chromedriver                        0x000000010d1af1b3 chromedriver + 680371\n10  chromedriver                        0x000000010d1b07ce chromedriver + 686030\n11  chromedriver                        0x000000010d567642 chromedriver + 4580930\n12  chromedriver                        0x000000010d56c9cc chromedriver + 4602316\n13  chromedriver                        0x000000010d54ce11 chromedriver + 4472337\n14  chromedriver                        0x000000010d56d746 chromedriver + 4605766\n15  chromedriver                        0x000000010d53e39c chromedriver + 4412316\n16  chromedriver                        0x000000010d58d868 chromedriver + 4737128\n17  chromedriver                        0x000000010d58da1e chromedriver + 4737566\n18  chromedriver                        0x000000010d59ee83 chromedriver + 4808323\n19  libsystem_pthread.dylib             0x00007ff8132701d3 _pthread_start + 125\n20  libsystem_pthread.dylib             0x00007ff81326bbd3 thread_start + 15\n\nScreenshot: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460399.png\nPageSource: file:///Users/olehlazeba/.selene/screenshots/1703165460399/1703165460399.html\n\n", "trace": "  File \"/Users/olehlazeba/PycharmProjects/qiwa-automation/venv/lib/python3.10/site-packages/selene/support/_logging.py\", line 105, in decorated\n    return for_(fn)\n  File \"/Users/olehlazeba/PycharmProjects/qiwa-automation/venv/lib/python3.10/site-packages/selene/core/wait.py\", line 141, in logic\n    raise self._hook_failure(failure)\n"}, "start": 1703165741033, "stop": 1703165761281}], "attachments": [{"name": "2023-12-21 15:36:01.487693.png", "source": "de1d1dac-1fab-416b-becf-d450dbc7e11e-attachment.png", "type": "image/png"}], "start": 1703165721098, "stop": 1703165761283, "uuid": "23891462-bddb-48d5-85a1-8385482aa495", "historyId": "ecc3510b9719a67164512910a896e410", "testCaseId": "ecc3510b9719a67164512910a896e410", "fullName": "tests.ui.user_management.test_user_management#test_error_for_user_without_um_service", "labels": [{"name": "parentSuite", "value": "tests.ui.user_management"}, {"name": "suite", "value": "test_user_management"}, {"name": "host", "value": "Macbook-Pro-Flora.local"}, {"name": "thread", "value": "54235-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.user_management.test_user_management"}], "links": [{"type": "tms", "url": "https://qiwa.testmo.net/repositories/26?case_id=7872", "name": "Testmo test case (7872)"}, {"type": "tms", "url": "https://qiwa.testmo.net/repositories/26?case_id=7882", "name": "Testmo test case (7882)"}, {"type": "tms", "url": "https://qiwa.testmo.net/repositories/26?case_id=7931", "name": "Testmo test case (7931)"}]}